### PR TITLE
mirror change to sha256d_preextend

### PR DESCRIPTION
**Pull request by sequencer**
after padding, W5->W14 is 0

### CODE REVIEW

**Comment by sequencer** [comment]
@pooler ping

**Comment by pooler** [comment]
@sequencer, I'm a bit swamped at the moment. I'll try to check this out in the next few days.

**Comment by sequencer** [comment]
ok thank you!

**Comment by pooler** [comment]
Sorry for the delay.

I haven't tested the patch, but I believe it is correct. However: after looking at the code, I think that the reason why I omitted this simplification years ago is that it does not bring any actual speedup (`sha256d_preextend` is only called once every few seconds), but does make the code less generic and less clear.

**Pull request closed without merging**
